from __future__ import annotations

import hashlib
from pathlib import Path

import pytest

from scripts.generate_verification_hash_lock import generate_hash_lock, main


def _write_requirements(path: Path, lines: list[str]) -> Path:
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return path


def _write_wheel(directory: Path, name: str, payload: bytes | None = None) -> Path:
    directory.mkdir(exist_ok=True)
    path = directory / name
    path.write_bytes(payload if payload is not None else name.encode("utf-8"))
    return path


def _hash(payload: bytes) -> str:
    return hashlib.sha256(payload).hexdigest()


def test_generate_hash_lock_is_canonical_and_includes_bootstrap(tmp_path: Path) -> None:
    requirements = _write_requirements(
        tmp_path / "exact.txt",
        [
            "--extra-index-url https://download.example.test/wheels",
            "",
            "Torch==2.11.0+cu128",
            "Demo_Pkg==1.2.0  # normalized by packaging",
        ],
    )
    wheelhouse = tmp_path / "wheelhouse"
    demo_bytes = b"demo wheel"
    pip_bytes = b"pip wheel"
    torch_bytes = b"torch wheel"
    _write_wheel(
        wheelhouse,
        "torch-2.11.0+cu128-cp311-cp311-win_amd64.whl",
        torch_bytes,
    )
    _write_wheel(wheelhouse, "pip-26.1.2-py3-none-any.whl", pip_bytes)
    _write_wheel(wheelhouse, "demo_pkg-1.2.0-py3-none-any.whl", demo_bytes)

    output = tmp_path / "hashed.txt"
    rendered = generate_hash_lock(
        requirements_path=requirements,
        wheelhouse=wheelhouse,
        output_path=output,
        bootstrap_requirements=["pip==26.1.2"],
    )

    assert output.read_bytes() == rendered.encode("utf-8")
    assert rendered == (
        "# Generated by scripts/generate_verification_hash_lock.py; do not edit.\n"
        "--require-hashes\n"
        "--only-binary=:all:\n"
        "--extra-index-url https://download.example.test/wheels\n"
        "\n"
        f"demo-pkg==1.2.0 --hash=sha256:{_hash(demo_bytes)}\n"
        f"pip==26.1.2 --hash=sha256:{_hash(pip_bytes)}\n"
        f"torch==2.11.0+cu128 --hash=sha256:{_hash(torch_bytes)}\n"
    )


def test_output_is_independent_of_wheel_creation_and_directive_order(
    tmp_path: Path,
) -> None:
    requirements_one = _write_requirements(
        tmp_path / "one.txt",
        [
            "--extra-index-url https://z.example.test/simple",
            "--index-url https://primary.example.test/simple",
            "--extra-index-url https://a.example.test/simple",
            "Beta==2",
            "alpha==1.0",
        ],
    )
    requirements_two = _write_requirements(
        tmp_path / "two.txt",
        [
            "--extra-index-url=https://a.example.test/simple",
            "--extra-index-url=https://z.example.test/simple",
            "--index-url=https://primary.example.test/simple",
            "alpha==1.0",
            "Beta==2",
        ],
    )
    wheelhouse_one = tmp_path / "wheels-one"
    wheelhouse_two = tmp_path / "wheels-two"
    for wheelhouse, names in (
        (
            wheelhouse_one,
            ["beta-2-py3-none-any.whl", "alpha-1.0-py3-none-any.whl"],
        ),
        (
            wheelhouse_two,
            ["alpha-1.0-py3-none-any.whl", "beta-2-py3-none-any.whl"],
        ),
    ):
        for name in names:
            _write_wheel(wheelhouse, name, name.split("-", 1)[0].encode())

    first = generate_hash_lock(
        requirements_path=requirements_one,
        wheelhouse=wheelhouse_one,
        output_path=tmp_path / "first.lock",
    )
    second = generate_hash_lock(
        requirements_path=requirements_two,
        wheelhouse=wheelhouse_two,
        output_path=tmp_path / "second.lock",
    )

    assert first == second
    assert first.index("--index-url") < first.index("--extra-index-url")
    assert first.index("https://a.example.test") < first.index("https://z.example.test")


@pytest.mark.parametrize(
    "requirement",
    [
        "demo>=1.0",
        "demo==1.*",
        "demo[extra]==1.0",
        "demo==1.0; python_version >= '3.11'",
        "demo @ https://example.test/demo.whl",
    ],
)
def test_rejects_non_exact_requirement_forms(
    tmp_path: Path,
    requirement: str,
) -> None:
    requirements = _write_requirements(tmp_path / "exact.txt", [requirement])
    wheelhouse = tmp_path / "wheelhouse"
    wheelhouse.mkdir()

    with pytest.raises(ValueError):
        generate_hash_lock(
            requirements_path=requirements,
            wheelhouse=wheelhouse,
            output_path=tmp_path / "lock.txt",
        )


def test_rejects_duplicate_normalized_package_pins(tmp_path: Path) -> None:
    requirements = _write_requirements(
        tmp_path / "exact.txt",
        ["Demo_Pkg==1.0", "demo-pkg==1.0"],
    )
    wheelhouse = tmp_path / "wheelhouse"
    wheelhouse.mkdir()

    with pytest.raises(ValueError, match="duplicate package pin"):
        generate_hash_lock(
            requirements_path=requirements,
            wheelhouse=wheelhouse,
            output_path=tmp_path / "lock.txt",
        )


def test_rejects_duplicate_bootstrap_package(tmp_path: Path) -> None:
    requirements = _write_requirements(tmp_path / "exact.txt", ["demo==1.0"])
    wheelhouse = tmp_path / "wheelhouse"
    _write_wheel(wheelhouse, "demo-1.0-py3-none-any.whl")

    with pytest.raises(ValueError, match="bootstrap package duplicates"):
        generate_hash_lock(
            requirements_path=requirements,
            wheelhouse=wheelhouse,
            output_path=tmp_path / "lock.txt",
            bootstrap_requirements=["Demo==1.0"],
        )


def test_rejects_missing_wheel_without_writing_output(tmp_path: Path) -> None:
    requirements = _write_requirements(
        tmp_path / "exact.txt",
        ["alpha==1.0", "beta==2.0"],
    )
    wheelhouse = tmp_path / "wheelhouse"
    _write_wheel(wheelhouse, "alpha-1.0-py3-none-any.whl")
    output = tmp_path / "lock.txt"

    with pytest.raises(ValueError, match="missing wheels for: beta"):
        generate_hash_lock(
            requirements_path=requirements,
            wheelhouse=wheelhouse,
            output_path=output,
        )

    assert not output.exists()


def test_rejects_extra_wheel(tmp_path: Path) -> None:
    requirements = _write_requirements(tmp_path / "exact.txt", ["alpha==1.0"])
    wheelhouse = tmp_path / "wheelhouse"
    _write_wheel(wheelhouse, "alpha-1.0-py3-none-any.whl")
    _write_wheel(wheelhouse, "beta-2.0-py3-none-any.whl")

    with pytest.raises(ValueError, match="extra package wheel"):
        generate_hash_lock(
            requirements_path=requirements,
            wheelhouse=wheelhouse,
            output_path=tmp_path / "lock.txt",
        )


def test_rejects_duplicate_wheels_for_one_pin(tmp_path: Path) -> None:
    requirements = _write_requirements(tmp_path / "exact.txt", ["alpha==1.0"])
    wheelhouse = tmp_path / "wheelhouse"
    _write_wheel(wheelhouse, "alpha-1.0-py3-none-any.whl")
    _write_wheel(wheelhouse, "alpha-1.0-cp311-cp311-win_amd64.whl")

    with pytest.raises(ValueError, match="duplicate wheels"):
        generate_hash_lock(
            requirements_path=requirements,
            wheelhouse=wheelhouse,
            output_path=tmp_path / "lock.txt",
        )


def test_rejects_wrong_wheel_version(tmp_path: Path) -> None:
    requirements = _write_requirements(tmp_path / "exact.txt", ["alpha==1.0"])
    wheelhouse = tmp_path / "wheelhouse"
    _write_wheel(wheelhouse, "alpha-2.0-py3-none-any.whl")

    with pytest.raises(ValueError, match=r"does not match alpha==1\.0"):
        generate_hash_lock(
            requirements_path=requirements,
            wheelhouse=wheelhouse,
            output_path=tmp_path / "lock.txt",
        )


@pytest.mark.parametrize(
    "filename",
    [
        "alpha-1.0.tar.gz",
        "alpha-1.0.zip",
    ],
)
def test_rejects_source_distributions(tmp_path: Path, filename: str) -> None:
    requirements = _write_requirements(tmp_path / "exact.txt", ["alpha==1.0"])
    wheelhouse = tmp_path / "wheelhouse"
    _write_wheel(wheelhouse, filename)

    with pytest.raises(ValueError, match="source distribution"):
        generate_hash_lock(
            requirements_path=requirements,
            wheelhouse=wheelhouse,
            output_path=tmp_path / "lock.txt",
        )


def test_rejects_invalid_wheel_filename(tmp_path: Path) -> None:
    requirements = _write_requirements(tmp_path / "exact.txt", ["alpha==1.0"])
    wheelhouse = tmp_path / "wheelhouse"
    _write_wheel(wheelhouse, "not-a-wheel.whl")

    with pytest.raises(ValueError, match="invalid wheel filename"):
        generate_hash_lock(
            requirements_path=requirements,
            wheelhouse=wheelhouse,
            output_path=tmp_path / "lock.txt",
        )


def test_rejects_unsupported_requirement_directive(tmp_path: Path) -> None:
    requirements = _write_requirements(
        tmp_path / "exact.txt",
        ["--find-links https://example.test/wheels", "alpha==1.0"],
    )
    wheelhouse = tmp_path / "wheelhouse"
    _write_wheel(wheelhouse, "alpha-1.0-py3-none-any.whl")

    with pytest.raises(ValueError, match="unsupported directive"):
        generate_hash_lock(
            requirements_path=requirements,
            wheelhouse=wheelhouse,
            output_path=tmp_path / "lock.txt",
        )


def test_rejects_output_inside_wheelhouse(tmp_path: Path) -> None:
    requirements = _write_requirements(tmp_path / "exact.txt", ["alpha==1.0"])
    wheelhouse = tmp_path / "wheelhouse"
    _write_wheel(wheelhouse, "alpha-1.0-py3-none-any.whl")

    with pytest.raises(ValueError, match="outside the wheelhouse"):
        generate_hash_lock(
            requirements_path=requirements,
            wheelhouse=wheelhouse,
            output_path=wheelhouse / "lock.txt",
        )


def test_cli_accepts_repeated_bootstrap_arguments(
    tmp_path: Path,
    capsys: pytest.CaptureFixture[str],
) -> None:
    requirements = _write_requirements(tmp_path / "exact.txt", ["alpha==1.0"])
    wheelhouse = tmp_path / "wheelhouse"
    _write_wheel(wheelhouse, "alpha-1.0-py3-none-any.whl")
    _write_wheel(wheelhouse, "pip-26.1.2-py3-none-any.whl")
    _write_wheel(wheelhouse, "wheel-0.47.0-py3-none-any.whl")
    output = tmp_path / "lock.txt"

    assert (
        main(
            [
                "--requirements",
                str(requirements),
                "--wheelhouse",
                str(wheelhouse),
                "--output",
                str(output),
                "--bootstrap",
                "pip==26.1.2",
                "--bootstrap",
                "wheel==0.47.0",
            ]
        )
        == 0
    )
    assert "wrote 3 hashed wheel pins" in capsys.readouterr().out
    assert "pip==26.1.2 --hash=sha256:" in output.read_text(encoding="utf-8")
    assert "wheel==0.47.0 --hash=sha256:" in output.read_text(encoding="utf-8")
